name: Graphle Backend NLP

on:
    push:
        branches:
            - nlp

jobs:
    build:
        runs-on: NLP

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Installing NPM Packages
              run: npm install
            - name: Build to JS
              run: npm run-script build
            - name: Restart PM2
              run: |
                  cp ../../../../ecosystem.config.js .
                  cp ../../../../learning-283013-9b7177e8ca72.json .
                  npm start
